### ISSUE TITLE
Error Running UI test

### ISSUE THREAD

**Issue by JunruTao** [masqu3rad3/tik_manager4#1]
heylo Arda,

Merry Christmas!

Been reading the code and I thought to give the tests a go. 
I tried to run the test file `ui_tests.py` and it throws me this error, and also crashes python program.

```
/usr/local/bin/python3.11 /Users/PeterTao/Documents/dev/tik_manager4/tests/ui_tests.py 
QWidget: Must construct a QApplication before a QWidget

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

Not sure what the reason is.

I am on a i7core macBook, 
python version: `3.11.1`
with latest `PyQt5`, `PySide2` and `pytest`.

from what I can trace it back, error happens on these 2 lines (line 7-8):
```python
from tik_manager4.ui.mcv.subproject_tree import TikProjectLayout
from tik_manager4.ui.mcv.task_tree import TikTaskLayout
```

I am not sure how Qt is integrated here. Any idea for me to run some of those test locally? 
(To get a general idea.)

**Comment by masqu3rad3** [comment]
Hi Tao,

Thanks for giving a try.
Currently the ui_tests.py is just a scratch file without any pytest integration. 
There are many things that can go wrong. Can you run it with a debugger and trace the error message?
Also that assumes that there is already a sample project file in your home folder called "t4_test_manual_DO_NOT_USE"
This project is getting created when you run the test_project pytests. (each time you run the tests it gets a reset)

You didn't specify if you are using MacOs or Windows on your mac, but I have  never tested any of this on a mac environment.

Can you try to run test_project and test_user pytest files inside the tests folder? Those are more proper pytests and if they can pass, that would mean we are on the right track.

Thanks

**Comment by JunruTao** [comment]
Thanks for your help, (and Yes, I am on a MacOS not windows.)

I've pull the latest dev branch and run `test_project` and `test_user` accordingly:
1. `test_project` &rarr; pass with flying colors, no errors. I can see all the folder and and files populated under my home folder.
2. `test_user` &rarr;  error; stopped right away:
Error as shown:

```
============================= test session starts ==============================
collecting ... 
tests/test_user.py:None (tests/test_user.py)
tests/test_user.py:5: in <module>
    class TestUser(object):
tests/test_user.py:10: in TestUser
    from tik_manager4.objects.main import Main  # importing main checks the common folder definition, thats why its here
tik_manager4/objects/main.py:6: in <module>
    from tik_manager4.objects import user, project
tik_manager4/objects/project.py:4: in <module>
    from tik_manager4.objects.subproject import Subproject
tik_manager4/objects/subproject.py:11: in <module>
    from tik_manager4.objects.task import Task
tik_manager4/objects/task.py:8: in <module>
    from tik_manager4.objects.category import Category
tik_manager4/objects/category.py:8: in <module>
    from tik_manager4.objects.work import Work
tik_manager4/objects/work.py:10: in <module>
    class Work(Settings, Entity):
tik_manager4/objects/work.py:11: in Work
    _dcc_handler = dcc.Dcc()
E   AttributeError: module 'tik_manager4.dcc' has no attribute 'Dcc'


collected 0 items / 1 error

=============================== 1 error in 0.27s ===============================
ERROR: not found: /Users/PeterTao/Documents/dev/tik_manager4/tests/test_user.py::TestUser
(no name '/Users/PeterTao/Documents/dev/tik_manager4/tests/test_user.py::TestUser' in any of [<Module test_user.py>])


Process finished with exit code 4

```

Any clues how to fix it?

**Comment by masqu3rad3** [comment]
Yes, I am getting the same error at the moment. Working on it.

**Comment by masqu3rad3** [comment]
I recently changed the way of the initialization. This was still stuck with the old method. I fixed that. Let me know if it works now.

**Comment by JunruTao** [comment]
> I recently changed the way of the initialization. This was still stuck with the old method. I fixed that. Let me know if it works now.

Great, This one passes with flying colors too. 
Does `test_user` generate any local files?

**Comment by masqu3rad3** [comment]
Yes it does. It creates a mockup_common folder and preferences files and <user>/TikManager4  folder with user setting files. 
These user setting files are VERY wip, essentially inherited from Tik v03
