### ISSUE TITLE
maya installation

### ISSUE THREAD

**Issue by ronnyascencio** [masqu3rad3/tik_manager4#102]
**Describe the bug**

**To Reproduce**
installation with draganddropme.py
after last pull request of the repository 

**Expected behavior**
install tik

**Screenshots**
shoudl install

![Screenshot from 2024-04-24 08-21-55](https://github.com/masqu3rad3/tik_manager4/assets/95187946/1319c308-1d11-4eaf-a68c-fe1abc1205f1)

notthing installed 

![Screenshot from 2024-04-24 08-22-14](https://github.com/masqu3rad3/tik_manager4/assets/95187946/344f2c71-a305-4175-b61e-e01b70424726)

**DCC**
Please complete the following information:
- Dcc name(s): Maya
- Dcc Version(s) 2024.2

**Desktop (please complete the following information):**
 - OS: linux
 - Versionrocky 8.9

**Additional context**
on 2023 its ok

**Comment by masqu3rad3** [comment]
Can you check the output shell while launching maya and copy paste its content?

Maya deployment happens with modules and actually the module pointer stays in the user/maya/modules directory (above all versions). It should be version agnostic. Meaning that when installed for Maya 2023, it should work for all Maya versions.

Can you also try to locate the module file? (user/maya/modules/tik_manager4.mod)
When you run this command from Maya's python script editor:
```
import os
os.getenv("MAYA_MODULE_PATH")
```
It should give you the paths that you can put that module file in. 
If the tik_manager4.mod is not in any of these paths, it cannot load it.

Are you launching maya with a wrapper command? MAYA_MODULE_PATH is an environment variable which can be overridden before launching maya.

**Comment by ronnyascencio** [comment]
okay I am runing from the app not from t command here is the screen shots 
![Screenshot from 2024-04-24 19-15-31](https://github.com/masqu3rad3/tik_manager4/assets/95187946/73e1e469-4c53-4348-ba56-6149a7e8d07c)
![Screenshot from 2024-04-24 19-09-59](https://github.com/masqu3rad3/tik_manager4/assets/95187946/bc036540-5b07-4edb-bbb4-b2d34e9717d7)
![Screenshot from 2024-04-24 19-08-41](https://github.com/masqu3rad3/tik_manager4/assets/95187946/f08eed25-1bf4-47c4-afbd-f51051c21c0f)

**Comment by ronnyascencio** [comment]
I run it on command line and i got this : 
![Screenshot from 2024-04-24 19-23-18](https://github.com/masqu3rad3/tik_manager4/assets/95187946/e891f393-a747-4c81-ac02-bd198b890b50)
also i set up my MAYA_MODULE_PATH  and looks like is not picking up 
![Screenshot from 2024-04-24 19-24-41](https://github.com/masqu3rad3/tik_manager4/assets/95187946/7efc662f-c33a-4daf-a739-d4134cbf06d5)

**Comment by ronnyascencio** [comment]
okay solved  the problem is  that if there any module that cant not be read by maya  the it wont read the module of tik so i delate the megascan module that has the error and it works now  thanks

**Comment by masqu3rad3** [comment]
Nice! Glad this resolved. Thanks for the updates.
