### ISSUE TITLE
[4.1.0] - Check for Updates not working

### ISSUE THREAD

**Issue by vNicolini** [masqu3rad3/tik_manager4#119]
**Describe the bug**
In Tik4 4.1.0 Standalone (not tested in integrations), the `Check for Updates` function under the `Help` menu appears to not do anything. 

**To Reproduce**

- Open Tik 4.1.0 Standalone
- `Help` > `Check for Updates`
- wait for nothing to happen

**Expected behavior**
I'd expect a pop-up notifying the user that a new version is available (incl version number) and maybe even a link to the latest release

https://github.com/masqu3rad3/tik_manager4/assets/57097563/95deb3ef-fc45-4013-ad0d-718035d889d7

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by masqu3rad3** [comment]
I will be implementing this feature as you described on the next release @vNicolini. You are right, it was until now just a placeholder.

I was thinking about an auto-update process but I think I will postpone it now as it might be a bit tricky to provide that functionality cross-platform.

I will gather the release info and pop-up a window with link(s) as you described.

I am also thinking to add a 'check updates automatically' option to the user settings. Maybe not each launch, but daily basis.

**Comment by vNicolini** [comment]
I Personally am not a fan of "auto-update" so i'm fine not having it at all. I prefer controlling the versions myself. 

> Maybe not each launch, but daily basis.

By default i'd say to have it weekly but let the user choose through a dropdown in the settings. (eg: daily, weekly, monthly, never)

**Comment by masqu3rad3** [comment]
sorry for the confusion. I meant checking for the updates automatically, not updating automatically.

I am against auto-update as well and not going to implement it (at least with the next release).
It will just check the update and inform the user with a pop-up if there is a new update. 
There will be a checkbox on this dialog like 'Don't remind me for this version' which will blacklist that release and skip auto-reminders for that one.

Manual update checker from the main menu will always provide the correct update information. The blacklist won't apply here.

I will stick with daily check I guess. It is happening under the hood and a very fast check. No need to complicate the settings ui with another option.

**Comment by vNicolini** [comment]
Fair enough, makes sense to me!
