### ISSUE TITLE
3ds Max 2025

### ISSUE THREAD

**Issue by ronnyascencio** [masqu3rad3/tik_manager4#135]
**Describe the bug**
this error apairs 

**To Reproduce**
click in all any icons in the tool bar of tik that is added to  th tool bar on 3ds max

**Expected behavior**

**Screenshots**

**DCC**
Please complete the following information:
- Dcc name(s): 3ds Max 
- Dcc Version(s) 2025.2

**Desktop (please complete the following information):**
 - OS: windows
 - Version 11

**Additional context**
![Screenshot 2024-08-11 143110](https://github.com/user-attachments/assets/31d54277-53b7-4125-81d6-345fe8f13b43)

**Comment by masqu3rad3** [comment]
Hi, it looks like the path to the tik manager is not defined properly in tik_path.ms and therefore it cannot find the module.

Can you make sure the path is defined correctly cross-checkin with the manual installation here:
https://tik-manager4.readthedocs.io/en/latest/installation/3dsmax.html

**Comment by ronnyascencio** [comment]
Hello, 

here is the  path i set to the tik_path.ms
![Screenshot 2024-08-11 184510](https://github.com/user-attachments/assets/c3e59ed2-5793-4600-aef3-bdd7a9298f4d)


and this is the path where is located the file :

C:\Users\ronny\AppData\Local\Autodesk\3dsMax\2025 - 64bit\ENU\scripts\startup

i tried with the "//" as the doc says but it gaves me a error on syntax  then i swithc to "/" and says no module find

**Comment by masqu3rad3** [comment]
if you need to do the double, it needs to be a double BACKSLASH: "\\"
I'll need to check the docs if I made mistake in there.

Other than that you cannot user double quote in here. Because double quote is used when wrapping the python.Execute command.

Python won't you allow use quotes of the same type in a nested manner.
So please correct it like this:

```
python.Execute "
import sys
tik_path = 'C://Program Files//TikWorks//tik_manager4//'
if not tik_path in sys.path:
    sys.path.append(tik_path)
"
```

Additionally, may I ask why you are not using Automatic Installer? 
You are on Windows. It seems like you installed with the exe installer (the installation folder suggests that)
Only thing you need to do is select the 3ds Max while doing the installation, and it should be good to go.

Or you if you just installed 3ds Max and dont want to re-install Tik Manager (I don't know why you would avoid that, it takes less than 20 seconds) You can run the `install_dccs.exe` in the tik_manager4/dist/tik4 folder and it will pop-up a CLI that you can easily install integrations.

**Comment by ronnyascencio** [comment]
I used automatic installer and it just create the "shelf " buttons but when i click on it it pops  the error that the  tik_manager4 module do not exist

i used the code you gave me to fix the "//"

it does not work i re installed  tik  and also run the isntall_dccs.exe 
 it just install the macros 
![Screenshot 2024-08-12 102903](https://github.com/user-attachments/assets/9c5c0182-857a-464f-8bee-c5086a72d173)

**Comment by masqu3rad3** [comment]
What happened to the `tik4_path.ms` file in your scripts/startup??

You need to put that in tik4_path.ms file:

```
python.Execute "
import sys
tik_path = 'C://Program Files//TikWorks//tik_manager4//'
if not tik_path in sys.path:
    sys.path.append(tik_path)
"
```

and restart. 

I have pretty much the same setup and works for me:

![image](https://github.com/user-attachments/assets/bb8b860c-1612-4479-af6a-6504ea3996b5)

**Comment by masqu3rad3** [comment]
You are right about the automatic installer Rony, I messed up something for the 3ds Max installer. It looks like its skipping the tik4_path.ms. I will fix that on next release.

Thanks a lot for flagging it.

**Comment by masqu3rad3** [comment]
can you try this:

- open a scripting editor
- change the language to python (from language menu)
- execute this:
```
import sys
print(sys.path)
```
-  and copy paste the contents that you see in the listener? (text will be okay no Screenshot necessary)

**Comment by ronnyascencio** [comment]
Here it is :
Welcome to MAXScript.


<string>:8: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Welcome to Python 3.11.8 (remotes/origin/adsk-contrib/3dsmax/cpython-3.11.8:f6b44603b1b, Mar  7 2024, 18:0) [MSC v.1938 64 bit (AMD64)].

['D:\\Dropbox\\Workstation\\Tools\\Prism\\Repos\\Prism\\Prism\\PythonLibs\\Python3', 'C:\\Program Files\\Prism2\\PythonLibs\\Python311\\pywin32_system32', 'C:\\Program Files\\Prism2\\PythonLibs\\Python311\\win32\\lib', 'C:\\Program Files\\Prism2\\PythonLibs\\Python311\\win32', 'c:\\programdata\\blackmagic design\\davinci resolve\\support\\developer\\scripting\\modules', 'C:\\Program Files\\TikWorks\\tik_manager4', 'C:\\Program Files\\Autodesk\\3ds Max 2025', 'C:\\Program Files\\Autodesk\\3ds Max 2025\\python311.zip', 'C:\\Program Files\\Autodesk\\3ds Max 2025\\Python\\DLLs', 'C:\\Program Files\\Autodesk\\3ds Max 2025\\Python\\Lib', 'C:\\Users\\ronny\\AppData\\Roaming\\Python\\Python311\\site-packages', 'C:\\Program Files\\Autodesk\\3ds Max 2025\\Python', 'C:\\Program Files\\Autodesk\\3ds Max 2025\\Python\\Lib\\site-packages', 'C:/Program Files/Prism2\\Scripts', 'C:\\Program Files\\Prism2\\Scripts', 'C:\\Program Files\\Prism2\\PythonLibs\\CrossPlatform', 'C:\\Program Files\\Prism2\\PythonLibs\\Python311', 'C:\\Program Files\\Prism2\\PythonLibs\\Python3', 'C:\\Program Files\\Prism2\\Scripts\\ProjectScripts', 'C:\\Program Files\\Prism2\\Plugins\\Apps', 'C:\\Program Files\\Prism2\\Plugins\\Custom', 'C:\\ProgramData\\Prism2\\plugins', 'C:\\ProgramData\\Prism2\\plugins\\3dsMax\\Scripts', 'C:\\ProgramData\\Prism2\\plugins\\Blender\\Scripts', 'C:\\ProgramData\\Prism2\\plugins\\Nuke\\Scripts', 'C:\\ProgramData\\Prism2\\plugins\\Maya\\Scripts', 'C:\\ProgramData\\Prism2\\plugins\\Houdini\\Scripts', 'C:\\ProgramData\\Prism2\\plugins\\Hub\\Scripts', 'C:\\ProgramData\\Prism2\\plugins\\PrismInternals\\Scripts', 'C:\\ProgramData\\Prism2\\plugins\\PrismInternals\\ExternalModules/windows\\CrossPlatform', 'C:\\ProgramData\\Prism2\\plugins\\PrismInternals\\ExternalModules/windows\\Python311', 'C:\\Program Files\\Prism2\\Plugins\\Apps\\Standalone\\Scripts', 'D:\\jobs\\SL\\00_Pipeline\\CustomModules\\Python', 'C://Program Files//TikWorks//tik_manager4//', 'c:\\programdata\\autodesk\\applicationplugins\\substancein3dsmax2025\\scripts\\python\\substance', 'c:\\programdata\\autodesk\\applicationplugins\\substancein3dsmax2025\\scripts\\python\\substance', 'c:\\users\\ronny\\appdata\\roaming\\autodesk\\applicationplugins\\vray3dsmax2025\\plugins\\max_usd']
>>>

**Comment by masqu3rad3** [comment]
Blimey, I cannot believe I fell for this! (again)!!!

You need to specify the parent folder of the tik_manager4 because it is a module itself, and its looking for that.

```
python.Execute "
import sys
tik_path = 'C:/Program Files/TikWorks'
if not tik_path in sys.path:
    sys.path.append(tik_path)
"
```

You don't need to double slash with when its a forward slash (`/`)

**Comment by ronnyascencio** [comment]
Oh perfect  now is working  Thank you for the help !

**Comment by masqu3rad3** [comment]
No worries!

The prism setup might be causing issues too, so better remove prism completely 😛

**Comment by ronnyascencio** [comment]
hahaha Im trying to...
