### ISSUE TITLE
Project purpose description should be less hidden

### ISSUE THREAD

**Issue by darkvertex** [masqu3rad3/tik_manager4#56]
As a curious visitor with zero knowledge of this project, it took me 2 clicks to go into Documentation and then [Overview](https://tik-manager4.readthedocs.io/en/latest/overview.html) to _finally_ learn that Tik Manager is an asset and project manager. (The first paragraph from the README says nothing about what it is or does.)

If you want to attract more users, maybe putting it clearer in the README and repo description could be a good idea?

**Comment by hannesdelbeke** [comment]
came here to say the same. 

i don't understand what tikmanager is , or what it does. even after reading the overview.
a screenshot and brief description would be very helpfull

the current description in the readme is too vague

**Comment by masqu3rad3** [comment]
Valid points.
I will update the readme.md

As for the documentation, it is still very early days. Frankly, I believe overview provides a good description but it needs to spread out to readme and home page for sure.

Thank you for your feedbacks, I always appreciate all inputs and contribution.

**Comment by masqu3rad3** [comment]
I have updated the readme, description. Also did a minor update on documentation.
I would appreciate your thoughts @darkvertex and @hannesdelbeke

**Comment by darkvertex** [comment]
@masqu3rad3 Much better!

I would add one last remark... The "Powered by PyCharm" in the repo README makes no sense to me. I mean, it's not a runtime, it's an IDE, and it's not like JetBrains is a sponsor or something.

I presume it's there because someone is a fan, used it to develop this and that's great, but I think it's just confusing seeing that in the README.

**Comment by masqu3rad3** [comment]
@darkvertex it is actually a sponsor.

Jetbrains is giving me non-commercial full licence specific to this repository. I don't have to put it there but thought it would be ethically appropriate.

So it is not a fan post.

**Comment by darkvertex** [comment]
Oh, that's pretty cool! Congrats.

Maybe change "Powered by" to "Sponsored by" in that case?

**Comment by masqu3rad3** [comment]
I knew this was coming :)
allright allright.  😄
