### ISSUE TITLE
Not to create new project.

### ISSUE THREAD

**Issue by VfxBoy** [masqu3rad3/tik_manager4#64]
Hello Sir,
This is an amazing tool and I can't thank you enough. 
I have installed the Tik Manager4 but I am unable to create any New project.  Every time I click I get this error.
![image](https://github.com/masqu3rad3/tik_manager4/assets/161374041/dbf3e67e-cd38-480e-b6ce-33c138d499b3)

I have tried login in with the password mentioned in users.json, but while doing that It is showing me the wrong password.

Kindly help me, I am new to this and I am sorry if I missed some steps.

Thank you

**Comment by masqu3rad3** [comment]
Hi, 

The default passwords for all users are 1234
The ones you see on the json files are hashes just a bit more security.

You can switch to the admin user and create a new user with the admin priviliges with your initials. Or you can keep using admin if you prefer.

Apologies for not being clear about the default password. On upcoming versions I will work on a proper user management UI and I will make sure to streamline the process a bit more.

Thanks.

**Comment by VfxBoy** [comment]
Hello Sir,

Thank you. It is working now.
