### ISSUE TITLE
Standalone exe launch error when the defined commons folder is empty

### ISSUE THREAD

**Issue by masqu3rad3** [masqu3rad3/tik_manager4#76]
**Describe the bug**
There is a known issue with the compiled standalone version.

After the initial fresh install, standalone version (windows version / .exe file) fails to create the necessary files inside the defined common folder.

**To Reproduce**
1. Define an empty folder as common folder
2. Launch tik4_standalone.exe

**Expected behavior**
Standalone exe version should be able to create the initial file like the unfrozen python version. 

**DCC**
- compiled standalone (windows) 

**Desktop:**
 - Windows versions
 - Standalone exe file only

**Workaround**

If you first the Tik Manager from a DCC (other than photoshop), these files are getting created and standalone version will work fine too.

Alternatively, the files can be copied manually from the defaults directory inside the tik manager insallation folder to the defined common folder.

**Comment by ballinger** [comment]
i get a segmentation fault if i cancel the file browser that pops open. what is the commons folder, or where should i point it to? im on rockylinux trying the latest stable tik_m. with houdini 20.5

**Comment by masqu3rad3** [comment]
> i get a segmentation fault if i cancel the file browser that pops open. what is the commons folder, or where should i point it to? im on rockylinux trying the latest stable tik_m. with houdini 20.5

I believe this is unrelated to the standalone version issue you are referring to. That one is only affecting the frozen exe standalone file and it was windows only. It should have been fixed with the current release as well.

Your issue is probably happening because you are trying to skip defining the common folder.

Common folder must be defined for Tik Manager to operate.

Simply define an empty folder where each user in your team can have access. The other users doesn't need to have write access but the admin (the one first defines the folder) must have read/write access there.

When defined, Tik Manager will populate the necessary files there.

For more info Check the docs
https://tik-manager4.readthedocs.io/en/latest/getting_started.html
