### ISSUE TITLE
blender Increment Version bug

### ISSUE THREAD

**Issue by bodibod** [masqu3rad3/tik_manager4#91]
**Describe the bug**
I can't Save increment my scene, gives me a Work not found
But when I do it from main UI and click Ingest it works
**To Reproduce**
I opened my project via Tik UI
I click on "tik new Version"

**Expected behavior**
should increment to next version
**Screenshots**

**DCC**
Please complete the following information:
-Blender
- 4.1

**Desktop (please complete the following information):**
 - Win WS
 - 10

**Additional context**
I will try on Linux later today (I am on Windows because I am using Substances with this specific project)

**Comment by masqu3rad3** [comment]
I think this happens only with the new version menu item. Looks like the 'new version' button on main ui works as expected.
Although they are essentially the same commands, the blender log says it is having trouble with thumbnail creation and throws an error.
I will fix or patch this at once.
Thank you for the feedback!

**Comment by masqu3rad3** [comment]
A fix merged and released:

https://github.com/masqu3rad3/tik_manager4/releases/tag/v4.0.91-beta

@bodibod when you have the chance, can you confirm that it is working?

**Comment by bodibod** [comment]
Let me check !

**Comment by bodibod** [comment]
All good, bug is gone on Windows, I will try on Linux later :)

**Comment by masqu3rad3** [comment]
Nice! Thank you for conforming.
