### ISSUE TITLE
Gaffer variables overwrite

### ISSUE THREAD

**Issue by ronnyascencio** [masqu3rad3/tik_manager4#97]
**Describe the bug**

**To Reproduce**
loading the project from tik UI

**Expected behavior**
is overwriting my existing defaults variables  and this should just overwrite the project name and root directory  variable 
and the frame range is not set acording to the project settings Defined  on tik
in this case this should be 1001 -1100

**DCC**
Please complete the following information:
-Gafferhq 1.4

**Desktop (please complete the following information):**
 - OS: linux
 - Version rocky 8.9

![tikproject_varaibles](https://github.com/masqu3rad3/tik_manager4/assets/95187946/085cd529-4897-4a0d-8c42-6865ee74afeb)
![gaffer_default_opened](https://github.com/masqu3rad3/tik_manager4/assets/95187946/8111288c-f673-410c-bb4b-5362a2819d55)

**Comment by masqu3rad3** [comment]
Hi, setting the projectRoot and project name totally valid point. This rolled intot the master branch and will be available on next release.

Frame ranges are not validated and forced when opening files deliberately. This is the same behaviour as the other DCCs. The frame ranges has to be checked while publishing. I will look into that (for all DCCs actually)
