### ISSUE TITLE
Ktana 6.0v4 conflict  with renderman 26

### ISSUE THREAD

**Issue by ronnyascencio** [masqu3rad3/tik_manager4#98]
**Describe the bug**

**To Reproduce**
1. Go to 'shelvs'
2. Click on 'main UI''
3. See error

**Expected behavior**
open the tik UI to chose the file to load or open a script 

**Screenshots**
![Screenshot from 2024-04-19 12-26-56](https://github.com/masqu3rad3/tik_manager4/assets/95187946/3a2dc706-2694-4a61-bf8e-ce0a39b397cc)

**DCC**
Please complete the following information:
- Dcc name(s): katana
- Dcc Version(s) [6.0v4

**Desktop (please complete the following information):**
 - OS: linux
 - Version rocky 8.9

this gets a conflict after install  renderman 26

**Comment by masqu3rad3** [comment]
This looks like an issue between the Qt shim and renderman. Interesting one, didn't see that before. I can try a couple of things but I need to replicate the issue. Is there a trial or non-commercial edition of renderman?

**Comment by ronnyascencio** [comment]
No comercial renderman is free to use renderman 26  it is doing the same for all version of katana and renderman 26 


You can get renderman for free

**Comment by masqu3rad3** [comment]
Hi, @ronnyascencio

I managed to replicate the issue with Katana 6.0v4, Renderman 26 and Windows. I found a solution which will most probably apply to linux too.

To workaround this, you can edit your init.py file under the .katana folder as follows:

```
# Tik Manager 4 [Start]
import sys
import os
tik_path = "PATH/TO/PARENT/FOLDER/OF/TIKMANAGER4/"
if not tik_path in sys.path:
    sys.path.append(tik_path)
os.environ["QT_PREFERRED_BINDING_JSON"] = '{"tik_manager4.ui.Qt": ["PyQt5"], "default":["PyQt5"]}'
# Tik Manager 4 [End]
```

Essentially the `import os` and `os.environ["QT_PREFERRED_BINDING_JSON"] = '{"tik_manager4.ui.Qt": ["PyQt5"], "default":["PyQt5"]}' lines added to override the QT pick up PyQT5. For some reason renderman installation messes with that up.

I am updating the installation guides and windows installer which will be available with next release.

Would be great if you can let me know if that works for you too.

Best

**Comment by ronnyascencio** [comment]
It works now no conflicts  from 6.0v4 and 6.5v3 with renderman and tik4

**Comment by masqu3rad3** [comment]
Fantastic! Thanks for the confirmation.
